parameters:
#    bash_nodes.example.class: Bash\NodesBundle\Example

services:
 blogger.symblog.admin.blog:
        class: Bash\NodesBundle\Admin\QuoteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Quote }
        arguments: [null, Bash\NodesBundle\Entity\Quote, BashNodesBundle:QuoteAdmin]

 blogger.symblog.admin.comment:
        class: Bash\NodesBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Entities, label: Comments }
        arguments: [null, Bash\NodesBundle\Entity\Comment,  BashNodesBundle:CommentAdmin]