security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /recent/1
            logout:
                            path:   /logout
                            target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$,    role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/register,  role: ROLE_ADMIN }
        - { path: ^/resetting, role: ROLE_ADMIN }
        - { path: ^/admin/,    role: ROLE_ADMIN }

        - { path: ^/random,    role: ROLE_USER }
        - { path: ^/recent/,   role: ROLE_USER }
        - { path: ^/best,      role: ROLE_USER }
        - { path: ^/add_quote, role: ROLE_USER }
        - { path: ^/add_code,  role: ROLE_USER }
        - { path: ^/govnocod,  role: ROLE_USER }
        - { path: ^/quotes/,   role: ROLE_USER }
        - { path: ^/post/,     role: ROLE_USER }
        - { path: ^/myquotes,  role: ROLE_USER }
        - { path: ^/edit/,     role: ROLE_USER }
        - { path: ^/dell/,     role: ROLE_USER }