parameters:
#    bash_user.example.class: Bash\UserBundle\Example

services:
#    bash_user.example:
#        class: %bash_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
